name: testtee
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4

 
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/icons/
  fonts:
    - family: Khula
      fonts:
        - asset: fonts/Khula-ExtraBold.ttf
          weight: 800